<?php
$xmlstr = <<<XML
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="(File per visualizzazione FatturaPA 1.2 - NON inviare).xsl"?>
<p:FatturaElettronica versione="FPA12" xmlns:p="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2" xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
  <FatturaElettronicaHeader>
    <DatiTrasmissione>
      <IdTrasmittente>
        <IdPaese>$data[IdPaese]</IdPaese>
        <IdCodice>$data[idCodice]</IdCodice>
      </IdTrasmittente>
      <ProgressivoInvio>$data[progressivoInvio]</ProgressivoInvio>
      <FormatoTrasmissione>$data[FormatoTrasmissione]</FormatoTrasmissione>
      <CodiceDestinatario>$data[CodiceDestinatario]</CodiceDestinatario>
    </DatiTrasmissione>
    <CedentePrestatore>
      <DatiAnagrafici>
        <IdFiscaleIVA>
          <IdPaese>$data[IdPaese]</IdPaese>
          <IdCodice>$data[idCodice]</IdCodice>
        </IdFiscaleIVA>
        <CodiceFiscale>$data[idCodice]</CodiceFiscale>
        <Anagrafica>
          <Denominazione>$data[DenominazioneSeller]</Denominazione>
        </Anagrafica>
        <RegimeFiscale>$data[RegimeFiscale]</RegimeFiscale>
      </DatiAnagrafici>
      <Sede>
        <Indirizzo>$data[IndirizzoSeller]</Indirizzo>
        <CAP>$data[CAPSeller]</CAP>
        <Comune>$data[ComuneSeller]</Comune>
        <Provincia>$data[provinceSeller]</Provincia>
        <Nazione>$data[NazioneSeller]</Nazione>
      </Sede>
      <IscrizioneREA>
        <Ufficio>$data[Ufficio]</Ufficio>
        <NumeroREA>$data[NumeroREA]</NumeroREA>
        <CapitaleSociale>$data[CapitaleSociale]</CapitaleSociale>
        <SocioUnico>$data[SocioUnico]</SocioUnico>
        <StatoLiquidazione>$data[StatoLiquidazione]</StatoLiquidazione>
      </IscrizioneREA>
      <Contatti>
        <Telefono>$data[Telefono]</Telefono>
        <Fax>$data[Fax]</Fax>
        <Email>$data[Email]</Email>
      </Contatti>
      <RiferimentoAmministrazione>$data[RiferimentoAmministrazione]</RiferimentoAmministrazione>
    </CedentePrestatore>
    <CessionarioCommittente>
      <DatiAnagrafici>
        <IdFiscaleIVA>
          <IdPaese>$data[IdPaese]</IdPaese>
          <IdCodice>$data[idCodice]</IdCodice>
        </IdFiscaleIVA>
        <Anagrafica>
          <Denominazione>$data[DenominazioneBuyer]</Denominazione>
        </Anagrafica>
      </DatiAnagrafici>
      <Sede>
        <Indirizzo>$data[IndirizzoBuyer]</Indirizzo>
        <CAP>$data[CAPBuyer]</CAP>
        <Comune>$data[ComuneBuyer]</Comune>
        <Provincia>$data[ProvinciaBuyer]</Provincia>
        <Nazione>$data[NazioneBuyer]</Nazione>
      </Sede>
    </CessionarioCommittente>
  </FatturaElettronicaHeader>
  <FatturaElettronicaBody>
    <DatiGenerali>
      <DatiGeneraliDocumento>
        <TipoDocumento>$data[TipoDocumento]</TipoDocumento>
        <Divisa>$data[Divisa]</Divisa>
        <Data>$data[Data]</Data>
        <Numero>$data[Numero]</Numero>
        <ImportoTotaleDocumento>$data[ImportoTotaleDocumento]</ImportoTotaleDocumento>
      </DatiGeneraliDocumento>
    </DatiGenerali>
    <DatiBeniServizi>
      <DettaglioLinee>
        <NumeroLinea>1</NumeroLinea>
        <Descrizione>$data[DescrizioneService]</Descrizione>
        <Quantita>$data[Quantita]</Quantita>
        <PrezzoUnitario>$data[PrezzoUnitario]</PrezzoUnitario>
        <PrezzoTotale>$data[PrezzoTotale]</PrezzoTotale>
        <AliquotaIVA>$data[AliquotaIVA]</AliquotaIVA>
      </DettaglioLinee>
      <DettaglioLinee>
        <NumeroLinea>2</NumeroLinea>
        <CodiceArticolo>
          <CodiceTipo>INTERNO</CodiceTipo>
          <CodiceValore>(NOTA)</CodiceValore>
        </CodiceArticolo>
        <Descrizione>$data[DescrizioneServiceTax]</Descrizione>
        <PrezzoUnitario>0.00</PrezzoUnitario>
        <PrezzoTotale>0.00</PrezzoTotale>
        <AliquotaIVA>$data[AliquotaIVA]</AliquotaIVA>
      </DettaglioLinee>
      <DatiRiepilogo>
        <AliquotaIVA>$data[AliquotaIVA]</AliquotaIVA>
        <ImponibileImporto>$data[PrezzoTotale]</ImponibileImporto>
        <Imposta>$data[Imposta]</Imposta>
        <EsigibilitaIVA>S</EsigibilitaIVA>
        <RiferimentoNormativo>$data[RiferimentoNormativo]</RiferimentoNormativo>
      </DatiRiepilogo>
    </DatiBeniServizi>
    <DatiPagamento>
      <CondizioniPagamento>$data[CondizioniPagamento]</CondizioniPagamento>
      <DettaglioPagamento>
        <ModalitaPagamento>$data[ModalitaPagamento]</ModalitaPagamento>
        <DataScadenzaPagamento>$data[DataScadenzaPagamento]</DataScadenzaPagamento>
        <ImportoPagamento>$data[ImportoPagamento]</ImportoPagamento>
        <IstitutoFinanziario>$data[IstitutoFinanziario]</IstitutoFinanziario>
        <IBAN>$data[IBAN]</IBAN>
      </DettaglioPagamento>
    </DatiPagamento>
  </FatturaElettronicaBody>
</p:FatturaElettronica>
XML;
?>